Update test execution steps
MediaIQ/heimdall pull request #14
Opened 2020-04-27 11:30 UTC by vaibsaraswat

#13 Update test execution steps

2020-04-28 07:18 UTC, tan31989 commented
@vaibsaraswat the gif is very small and does not show prominently the things you are trying to implement. Can we do this with a gif where we can also blur others?

2020-05-05 07:25 UTC, aakash17kc approved these changes

2020-05-06 18:30 UTC, ntantri requested changes
Can we ensure the gif is a bit bigger in size?

2020-06-10 05:04 UTC, ntantri approved these changes

2020-06-10 08:11 UTC, merged