Heimdall 19
MediaIQ/heimdall pull request #20
Opened 2020-05-05 07:03 UTC by aakash17kc

Update karate version to 0.9.5. Updated heimdall.application version to 1.0.1

2020-05-05 09:37 UTC, vaibsaraswat approved these changes

2020-05-06 18:30 UTC, ntantri requested changes

2020-05-06 18:30 UTC, ntantri commented on heimdall.sample-client/src/test/java/com/miqdigital/cucumber_runner/javasample/KarateTestRunner.java
> +    Results results = Runner.path(karateOutputPath).tags("@regression").parallel(10);
Can we not have 10 parameterized? It might become a bit hardcoding to 10 right?

2020-05-08 07:20 UTC, aakash17kc commented on heimdall.sample-client/src/test/java/com/miqdigital/cucumber_runner/javasample/KarateTestRunner.java
> +    Results results = Runner.path(karateOutputPath).tags("@regression").parallel(10);
This method is not called anywhere. So parameterizing is not an option. Most we can do is read it from a properties file but that would require more code. Also, this is just a demo class of how Heimdall can be used to get test results.

2020-05-09 15:33 UTC, tan31989 commented on heimdall.sample-client/src/test/java/com/miqdigital/cucumber_runner/javasample/KarateTestRunner.java
> +    Results results = Runner.path(karateOutputPath).tags("@regression").parallel(10);
Sure.

2020-05-09 16:22 UTC, ntantri approved these changes

2020-05-09 16:22 UTC, merged